# The site theme
theme: jekyll-theme-slate

# Make a build language environment
language: shell

# The project version
version: "v0.8.12"

# cprtsrs => Copyright to SunbossRS

# Make building status
status:
  - Build version
  - git.flow.project.cprtsrs
